##########################################
#                 Config                 #
##########################################

CONFIG: # BOT CONFIGURATION
  BOT:
    TOKEN: " "
# MUSIC CONFIGURATION
  MUSIC:
    EMIT_NEW_SONG_ONLY: false
    LEAVE_ON_EMPTY: false
    LEAVE_ON_FINISH: false
    LEAVE_ON_STOP: false
    NSFW: true
    EMPTY_COOLDOWN: 25
